### ISSUE TITLE
VII:2(j): selectionCriteria again?

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting-extensions/government-procurement-agreement#30]
continuing https://github.com/open-contracting-extensions/government-procurement-agreement/pull/26#discussion_r450892349

You mentioned on the call that certain keywords lead you to think this clause is related to selection criteria, but

- selection criteria are clearly mentioned in the next clause VII:2(k)
- eligibility criteria seem to be mentioned nowhere else (although the GPA may not mention them at all)

Do I repeat the guidance given in the next clause?

I just find that the GPA having two neighbour clauses about selection criteria is unlikely.

**Comment by jpmckinney** [comment]
VII:2(k) is specifically about the criteria for pre-selection (i.e. there is a maximum number of qualified suppliers, and as such the criteria that distinguish the limited number of qualified suppliers need to be weighted or ranked criteria).

VII:2(j) is more broadly about the criteria for pre-qualification (which can just be pass/fail).

In practice, no distinction is made, because to be efficient, you'd usually start with the pass/fail criteria anyway, and if there are failures you don't bother assessing the ranked or weighted criteria for that supplier.

Also, it's easy to disambiguate the two, based on whether they are pass/fail or not. So, the data doesn't need an additional marker to distinguish them.
